export const START_LOADING = 'START_LOADING';
export const FINISH_LOADING = 'FINISH_LOADING';
export const SET_CAMPERS = 'SET_CAMPERS'
export const ADD_FAVORITE_CARD = 'ADD_FAVORITE_CARD'
export const REMOVE_FAVORITE_CARD = 'REMOVE_FAVORITE_CARD'
export const SET_FAVORITE_CARDS = 'SET_FAVORITE_CARDS'
export const SET_FILTERED_CAMPERS = 'SET_FILTERED_CAMPERS'